title:              Songhyun IM 
email:              dnfl9020@gmail.com
description:        Songhyun's analysis
author:             Songhyun IM 
baseurl:            ""
url:                "https://shyun0406.github.io"

# Social Profiles
twitter_username:   
github_username:    shyun0406
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
